#!/usr/bin/env ruby

require 'csv'

input = "~/Desktop/interstella.mkv"
hlf_name = "resized.mkv"

interval = 1
`rm 00*.mkv`
`rm 00*.gif`
`rm palette.png`

def run command
  puts command
  `#{command}`
end

(['0.']+CSV.read("cuts3.csv").flatten).each_cons(2).map do |start_time, end_time|
  file_name = start_time[0..(start_time.index('.')||0)+3].ljust(7,'0')
  mkv_name = "#{file_name}.mkv"
  gif_name = "#{file_name}.gif"
  duration = end_time.to_f - start_time.to_f
  run %(ffmpeg -ss #{start_time} -i #{input} -t #{duration} #{mkv_name})
  run %(ffmpeg -i #{mkv_name} -vf fps=15,scale=400:220:flags=lanczos,palettegen palette.png)
  run %(ffmpeg -i #{mkv_name} -vf "scale=116:64, crop=64:64:26:0" #{hlf_name})
  run %(ffmpeg -i #{hlf_name} -i palette.png -filter_complex "fps=15,scale=32:32:flags=lanczos[x];[x][1:v]paletteuse" #{gif_name})
  run %(rm #{mkv_name})
  run %(rm #{hlf_name})
  run %(rm palette.png)
end
