#!/usr/bin/env ruby

input = "input.mkv"

interval = 1
`rm 00*.mkv`
`rm 00*.gif`
`rm palette.png`

def run command
  puts command
  `#{command}`
end

(0..0).each do |h|
  (0..10).each do |m|
    (0..59).step(interval).each do |s|

      start_time = "%02d:%02d:%02d" % [h, m, s]
      length = "00:%02d" % interval
      file_name = "%02d%02d%02d-%02d%02d%02d" % [h, m, s, h, m, s+interval]
      mkv_name = "#{file_name}.mkv"
      gif_name = "%02d%02d%02d.gif" % [h,m,s]

      # `ffmpeg -ss #{start_time} -i #{input} -t #{length} #{mkv_name}`
      # `ffmpeg -i #{mkv_name} -vf fps=15,scale=400:220:flags=lanczos,palettegen palette.png`
      # `ffmpeg -i #{mkv_name} -i palette.png -filter_complex "fps=15,scale=400:220:flags=lanczos[x];[x][1:v]paletteuse" #{gif_name}`
      # `rm #{mkv_name}`
      # `rm palette.png`

      run %(ffmpeg -ss #{start_time} -i #{input} -t #{length} #{mkv_name})
      run %(ffmpeg -i #{mkv_name} -vf fps=15,scale=400:220:flags=lanczos,palettegen palette.png)
      run %(ffmpeg -i #{mkv_name} -vf "scale=116:64, crop=64:64:26:0" #{file_name}-resized.mkv)
      run %(ffmpeg -i #{file_name}-resized.mkv -i palette.png -filter_complex "fps=15,scale=64:64:flags=lanczos[x];[x][1:v]paletteuse" #{gif_name})
      run %(rm #{mkv_name})
      run %(rm #{file_name}-resized.mkv)
      run %(rm palette.png)
    end
  end
end

